name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master
env: 
  NODE_VERSION: 20.19.0 # Check support on azure before updating
  PNPM_VERSION: 10.6.3
  NODE_ENV: production
  PAYLOAD_SECRET: ${{ secrets.PAYLOAD_SECRET }}
  ALTCHA_HMAC_KEY: ${{ secrets.ALTCHA_HMAC_KEY }}
  AZURE_DYNAMIC_PREVIEW_URL: https://gray-bay-092da2e03-${{github.event.number}}.westeurope.6.azurestaticapps.net

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    environment: 
      name: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' && 'Production' || 'Preview' }}
      url: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' && vars.NEXT_PUBLIC_SERVER_URL || env.AZURE_DYNAMIC_PREVIEW_URL }}
    env:
      DATABASE_URI: ${{ secrets.DATABASE_URI }}
      NEXT_PUBLIC_SERVER_URL: ${{ inputs.environment.url }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Use pnpm ${{ env.PNPM_VERSION }}
        uses: pnpm/action-setup@v3
        with:
          version: ${{ env.PNPM_VERSION }}
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm
      - uses: actions/cache@v4
        with:
          path: |
            ${{ env.PNPM_HOME }}
            ${{ github.workspace }}/apps/website/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-
      - name: Install packages
        run: NODE_ENV=development pnpm install
      - name: Migrate database
        working-directory: ./apps/website
        run: pnpm run payload migrate
      - name: Build
        working-directory: ./apps/website
        run: pnpm run payload generate:importmap && NEXT_TELEMETRY_DISABLED=1 pnpm run build
      - name: Deploy
        id: deploy
        # if: ${{ !env.ACT || env.DEPLOY == 'true' }}
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GRAY_BAY_092DA2E03 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          production_branch: "master"
          action: "upload"
          skip_app_build: true
          skip_api_build: true
          app_location: "./apps/website"
          api_build_command: "rm -rf ./node_modules/@next/swc-*"
        env:
          skip_deploy_on_missing_secrets: true
          NEXT_PUBLIC_SERVER_URL: ${{ inputs.environment.url }}
          DATABASE_URI: ${{ secrets.DATABASE_URI }}

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GRAY_BAY_092DA2E03 }}
          action: "close"
