name: Azure Static Web Apps CI/CD
permissions: 
  actions: write
  pull-requests: read
  security-events: read
  id-token: write

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master
env: 
  NODE_VERSION: 20.19.0 # Check support on azure before updating
  PNPM_VERSION: 10.6.3
  NODE_ENV: production
  AZURE_DEPLOYMENT_URL:  https://zealous-rock-0009d2403${{ github.event.number && format('-{0}', github.event.number) }}.westeurope.6.azurestaticapps.net
  NEXT_PUBLIC_SERVER_URL: ${{ vars.NEXT_PUBLIC_SERVER_URL }}
  GH_TOKEN: ${{ github.token }}
  PAYLOAD_SECRET: ${{ secrets.PAYLOAD_SECRET }}
  ALTCHA_HMAC_KEY: ${{ secrets.ALTCHA_HMAC_KEY }}
  NEXT_PUBLIC_PLAUSIBLE_API_KEY: ${{ secrets.NEXT_PUBLIC_PLAUSIBLE_API_KEY}}

jobs:
  build:
    if: (github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')) && github.events.pull_request.draft == false
    runs-on: ubuntu-latest
    name: Build
    environment: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' && 'Production' || 'Preview' }}
    env:
      SMTP_SKIP_VERIFY: ${{ vars.SMTP_SKIP_VERIFY }}
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      DATABASE_URI: ${{ secrets.DATABASE_URI }}
    steps:
      - uses: actions/checkout@v3
      - name: Set dynamic server url
        if: github.event_name == 'pull_request'
        run: echo "NEXT_PUBLIC_SERVER_URL=${{ env.AZURE_DEPLOYMENT_URL }}" >> $GITHUB_ENV
      - name: Use pnpm ${{ env.PNPM_VERSION }}
        uses: pnpm/action-setup@v3
        with:
          version: ${{ env.PNPM_VERSION }}
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm
      - uses: actions/cache@v4
        with:
          path: |
            ${{ env.PNPM_HOME }}
            ${{ github.workspace }}/apps/website/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-
      - name: Install packages
        run: NODE_ENV=development pnpm install
      - name: Migrate database
        working-directory: ./apps/website
        run: pnpm run payload migrate
      - name: Build
        working-directory: ./apps/website
        run: pnpm run payload generate:importmap && NEXT_TELEMETRY_DISABLED=1 pnpm run build && rm -rf ./node_modules/@swc ./node_modules/@babel ./node_modules/@tailwindcss
      - uses: actions/cache@v4
        name: Cache build
        id: workflow-cache
        with:
          path: ./*
          key: ${{ github.sha }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    environment: 
      name: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' && 'Production' || 'Preview' }}
      url: ${{ env.NEXT_PUBLIC_SERVER_URL }}
    env:
      DATABASE_URI: ${{ secrets.DATABASE_URI }}
    steps:
      - uses: actions/cache@v4
        name: Use cache
        id: workflow-cache
        with:
          path: ./*
          key: ${{ github.sha }}
      - name: Set dynamic server url
        if: github.event_name == 'pull_request'
        run: echo "NEXT_PUBLIC_SERVER_URL=${{ env.AZURE_DEPLOYMENT_URL }}" >> $GITHUB_ENV
      - name: Deploy
        id: deploy
        if: ${{ !env.ACT || env.DEPLOY == 'true' }}
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ZEALOUS_ROCK_0009D2403 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          production_branch: "master"
          action: "upload"
          skip_app_build: true
          skip_api_build: true
          app_location: "./apps/website"
          api_build_command: "rm -rf ./node_modules/@next/swc-*"
          #deployment_environment: ${{ env.GITHUB_REF_NAME }}
        env:
          skip_deploy_on_missing_secrets: true
          SMTP_SKIP_VERIFY: ${{ env.SMTP_SKIP_VERIFY }}
      - name: Login to Azure via OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Configure runtime app settings
        uses: azure/cli@v2
        with:
          inlineScript: |
            if [ "${{github.ref}}" = "refs/heads/master" ]; then ENV="default"; else ENV="${{ github.event.number }}"; fi
            
            az staticwebapp appsettings set \
              --name "website" \
              --environment-name "$ENV" \
              --setting-names \
                  "PAYLOAD_SECRET=${{ secrets.PAYLOAD_SECRET }}" \
                  "NEXT_PUBLIC_SERVER_URL=${{ env.NEXT_PUBLIC_SERVER_URL }}" \
                  "DATABASE_URI=${{ secrets.DATABASE_URI }}" \
                  "SMTP_HOST=${{ vars.SMTP_HOST }}" \
                  "SMTP_PORT=${{ vars.SMTP_PORT }}" \
                  "SMTP_USER=${{ secrets.SMTP_USER }}" \
                  "SMTP_PASS=${{ secrets.SMTP_PASS }}" \
                  "AZURE_STORAGE_ACCOUNT_BASEURL=${{ secrets.AZURE_STORAGE_ACCOUNT_BASEURL }}" \
                  "AZURE_STORAGE_CONNECTION_STRING=${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}" \
                  "AZURE_STORAGE_CONTAINER_NAME=${{ vars.AZURE_STORAGE_CONTAINER_NAME }}" \
                  "ALTCHA_HMAC_KEY=${{ secrets.ALTCHA_HMAC_KEY }}" \
                  "SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}" \
                  "NEXT_PUBLIC_PLAUSIBLE_API_KEY=${{ secrets.NEXT_PUBLIC_PLAUSIBLE_API_KEY}}" \
              --only-show-errors
        env:
          AZURE_CLIENT_ID:  ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_TENANT_ID:  ${{ secrets.AZURE_TENANT_ID }}
      - name: Cleanup workflow cache
        if: always()
        run: gh cache delete ${{ github.sha }}

  close_pull_request:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ZEALOUS_ROCK_0009D2403 }}
          action: "close"
